language: R
sudo: false
cache:
- packages

before_deploy: Rscript -e 'install.packages("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master